### ISSUE TITLE
Corner case: PublishAcknowledge times out and recieves ack in parallell

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#15]
My system had a slight hick-up and the timer for publish acknowledge expired on one thread (`[12]`) while another thread (`[27]`) received an ack for the same message. This caused the application to throw a `KeyNotFoundException`.

This happens _very_ seldom, but should be fixed nevertheless. See logs below

```
2016-01-21 09:25:47,554 [27] [Information]  Recieved ack for 1 with multiple set to 'False'
2016-01-21 09:25:48,640 [12] [Warning]  Ack for 1 has timed out.
2016-01-21 09:25:49,258 [27] [Debug]  Disposed ack timer for 1
2016-01-21 09:25:50,881 [27] [Debug]  Message with delivery tag 1 has been acknowledged by broker.
2016-01-21 09:25:52,159 [12] [Fatal]  Unhandled exception: "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at RawRabbit.Common.PublishAcknowledger.<>c__DisplayClass8_0.<GetAckTask>b__0(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()"
```

**Comment by pardahlman** [comment]
This fix will be part of upcoming release
