### ISSUE TITLE
StackOverflowException occures when subscribeMethod throws an exception using dotnet core

### ISSUE THREAD

**Issue by srollinet** [pardahlman/RawRabbit#150]
When subscribeMethod throws an exception, I get a StackOverflowException caused by Newtonsoft.Json (I don't know if it is related to #136)

you can easily reproduce it with the following code, using version 1.10.2

```c#
        public static void Main(string[] args)
        {
            var client = BusClientFactory.CreateDefault();
            client.SubscribeAsync<BasicMessage>(async (msg, context) =>
            {
                throw new Exception("boom!");
            });
            client.PublishAsync(new BasicMessage());
        }

        public class BasicMessage
        {
        }
```

**Comment by pardahlman** [comment]
Your code looks a lot like [this test](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/Features/MessageHandlerExceptionTests.cs#L63) for when a subscriber throws. Could you provide me with a stack trace?

Don't think this relates to #136, as that only occurs with message context that hold complex Funcs.

**Comment by srollinet** [comment]
Unfortunately a StackOverflowException has no stack trace.

I can give you the top of the stack if it helps.
![image](https://cloud.githubusercontent.com/assets/12350967/20461957/bd32e994-af0e-11e6-83c6-c0edc1c1f7e5.png)

Then I have only calls to SerializeObject until the maximum number of stack frames supported is exceeded.

Here is the entire code:
[TestRabbit.zip](https://github.com/pardahlman/RawRabbit/files/601945/TestRabbit.zip)

**Comment by pardahlman** [comment]
@srollinet I tried to reproduce this when you reported it, without any success. It just struck me that I was running under 4.5.1 and furthermore I believe I know what the problem is.

`RawRabbit` executes all message handlers with an `IErrorHandlingStrategy`. The default strategy for exceptions in a subscribe message handler is to publish the message on an error exchange together with metadata, including the thrown exception.

Serialization of Exception in dotnet core is [not supported](https://github.com/dotnet/corefx/issues/6564), which is [exactly what we're doinig here](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/ErrorHandling/DefaultStrategy.cs#L138).

You can temporary mitigate the issue by implement your own error handler and override `OnSubscriberExceptionAsync`.

I'm open fora discussion as for what the best approach is here. I think it makes sense to get some information about the exception throw, when etc. Perhaps we should just use the [`MessageHandlerExceptionInformation`](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/Exceptions/MessageHandlerExceptionInformation.cs) here. @ritasker any thoughts? As a side note, should we include the serialized message or the raw `Body` prop from the delivery args?

**Comment by srollinet** [comment]
Sorry, I forgot to mention it was dotnet core. I changed the title.

I will try with with a custom error handler for now.

**Comment by pardahlman** [comment]
No worries, I'm glad you reported this so we can update it.

**Comment by ritasker** [comment]
I have been able to replicate the issue. 
I have also implemented a version of `IMessageSerializer` that uses [ServiceStack.Text](https://github.com/ServiceStack/ServiceStack.Text), see [here](https://gist.github.com/ritasker/8c0dce84cfc7bfb0f14494a260a5099a). This does not throw a `StackOverflowException`. 
You can reproduce the exception thrown by JSON.Net with the following code.
```
public static void Main(string[] args)
{
    try
    {
        throw new Exception("boom!");
    }
    catch (Exception ex)
    {
        var serializer = new JsonSerializer();
        string json;
        using (var sw = new StringWriter())
        {
            serializer.Serialize(sw, ex);
            json = sw.GetStringBuilder().ToString();
        }

        var msgBytes = Encoding.UTF8.GetBytes(json);
        Console.WriteLine(msgBytes);
    }
    Console.ReadLine();
}
```
It throws the following exception on the `serializer.Serialize(sw, ex);` line.
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'EntryPoint' with type 'System.Reflection.RuntimeMethodInfo'. Path 'TargetSite.Module.Assembly'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(TextWriter textWriter, Object value)
   at ConsoleApplication.Program.Main(String[] args) in /Users/richard/Documents/SourceCode/RabbitException/Program.cs:line 34
```

I am not sure if this is related to issue https://github.com/dotnet/coreclr/issues/2715 or not.
Further investigation required.
