### ISSUE TITLE
Connection will not be resumed

### ISSUE THREAD

**Issue by petr-kirillov** [pardahlman/RawRabbit#258]
I've just updated to .NET Core 2.0 and RawRabbit 2.0.0-beta8

I noted a resiliency issue. Once I hit 'Unable to connect to broker' in `RawRabbit.Channel.ChannelFactory` the connection will not be resumed. Although my broker was perfectly back online. If I stop/start my service, all good again.

Extract from my log:
```
[15:58:46] [INF] [$11] RawRabbit.Channel.ChannelFactory
    Unable to connect to broker
[15:58:46] [ERR] [$4]
    Unhandled exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:5672
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   --- End of inner exception stack trace ---
   at RawRabbit.Channel.ChannelFactory.ConnectToBroker()
   at RawRabbit.Channel.ChannelFactory..ctor(IConnectionFactory connectionFactory, RawRabbitConfiguration config, ChannelFactoryConfiguration channelConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

```
[16:01:41] [ERR] [$4]
    Unhandled exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:5672
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   --- End of inner exception stack trace ---
   at RawRabbit.Channel.ChannelFactory.ConnectToBroker()
   at RawRabbit.Channel.ChannelFactory..ctor(IConnectionFactory connectionFactory, RawRabbitConfiguration config, ChannelFactoryConfiguration channelConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at RawRabbit.DependencyInjection.SimpleDependencyInjection.CreateInstance(Type implementationType, IEnumerable`1 additional)
```

**Comment by pardahlman** [comment]
Hi, @petr-kirillov thanks for reporting this. Can you provide a code snippet or a step-by-step on how to reproduce this?

Thanks!

**Comment by pardahlman** [comment]
Closing this for now. Feel free to reopen and provide more information.

**Comment by zainvegeta** [comment]
I am facing a similar issue.I am not able to completely traceout how to reproduce this.but i have logs of the operation i previously executed.i am adding it below

{"@t":"2019-10-24T02:31:33.2314541Z","@mt":"Failed while executing {myRPCMethod} for enterprise = enterprise_{guid} via agent ={guid},"@l":"Error","@x":"System.TimeoutException: The request '{guid}' with routing key '{guid}' timed out after 0:00:50.\r\n   at RawRabbit.Operations.Request.Middleware.RequestTimeoutMiddleware.InvokeAsync(IPipeContext context, CancellationToken token)\r\n   at RawRabbit.Pipe.Middleware.QueueBindMiddleware.InvokeAsync(IPipeContext context, CancellationToken token)\r\n   at RawRabbit.Pipe.Middleware.ExchangeDeclareMiddleware.InvokeAsync(IPipeContext context, CancellationToken token)\r\n   at RawRabbit.Pipe.Middleware.ExchangeDeclareMiddleware.InvokeAsync(IPipeContext context, CancellationToken token)\r\n   at RawRabbit.Pipe.Middleware.QueueDeclareMiddleware.InvokeAsync(IPipeContext context, CancellationToken token)\r\n   at RawRabbit.BusClient.InvokeAsync(Action`1 pipeCfg, Action`1 contextCfg, CancellationToken token)\r\n   at RawRabbit.RequestExtension.RequestAsync[TRequest,TResponse](IBusClient client, TRequest message, Action`1 context, CancellationToken ct)\r\n   

{"@t":"2019-10-24T06:40:29.8402902Z","@mt":"Connection was shutdown by {Initiator}. ReplyText {ReplyText}","@l":"Warning","Initiator":"Library","ReplyText":"End of stream","SourceContext":"RawRabbit.Channel.ChannelFactory"}

any suggeston to overcome this.Because once this happend my API based on this will all hangup

and throws this response for any incomming calls

{"@t":"2019-10-24T06:40:48.0603095Z","@mt":"Unable to declare queue","@l":"Error","@x":"System.NotSupportedException: Pipelining of requests forbidden\r\n   at RabbitMQ.Client.Impl.RpcContinuationQueue.Enqueue(IRpcContinuation k)\r\n   at RabbitMQ.Client.Impl.ModelBase.Enqueue(IRpcContinuation k)\r\n   at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)\r\n   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)\r\n   at RawRabbit.Common.TopologyProvider.DeclareQueue(QueueDeclaration queue)\r\n   at RawRabbit.Common.TopologyProvider.EnsureWorker()","SourceContext":"RawRabbit.Common.TopologyProvider"}
