### ISSUE TITLE
Custom IMessageSerializer on 1.10.4 .net core 2.0

### ISSUE THREAD

**Issue by jonnysparkplugs** [pardahlman/RawRabbit#293]
Hi,

I'm having problems trying to register a customer serializer (I think). Basically when I do a `RequestAsync`

I'm getting an exception thrown:
`-		$exception	{System.ArgumentNullException: Value cannot be null.
Parameter name: typeName
   at RawRabbit.Operations.Requester`1.<>c__15`2.<SendRequestAsync>b__15_2(Task`1 tResponse)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)'

I believe its because its failing to parse the message. 

I have a node service that is listening to the rpc message and it seems to be working outside of raw rabbit.

My configuration is as follows:

```
                serviceCollection
                 .AddRawRabbit<AdvancedMessageContext>(config => {
                     config.AddJsonFile(configFiles["rawRabbitSettings.json"]);
                 }, container =>
                 {
                     container.AddSingleton<ILogger>(fileLogger);
                     container.AddSingleton<IMessageSerializer, RabbitSerializer>();
                 });
```
```
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using JsonSerializer = RawRabbit.Serialization.JsonMessageSerializer;

namespace Test
{
	public class RabbitSerializer : JsonSerializer
    {
        public RabbitSerializer() : base(new Newtonsoft.Json.JsonSerializer
        {
            TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple,
            Formatting = Formatting.None,
            CheckAdditionalContent = true,
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            ObjectCreationHandling = ObjectCreationHandling.Auto,
            DefaultValueHandling = DefaultValueHandling.Ignore,
            TypeNameHandling = TypeNameHandling.Auto,
            ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
            MissingMemberHandling = MissingMemberHandling.Ignore,
            PreserveReferencesHandling = PreserveReferencesHandling.None,
            NullValueHandling = NullValueHandling.Ignore
        })
        { }
    }
}
```
Am i missing something very basic?

**Comment by jonnysparkplugs** [comment]
Its crashing in

```public object Deserialize(BasicDeliverEventArgs args)```

in RawRabbit\Serialization\JsonMessageSerializer.cs as Type is null, however the service i'm connecting to doesn't set the Type field

**Comment by jonnysparkplugs** [comment]
Figured it out, the header data was missing in the payload
